### ISSUE TITLE
Tailwind css

### ISSUE THREAD

**Issue by gggglglglg** [brc-dd/next-hash-classnames#1]
does not work with tailwind css
How do make it work?

**Comment by brc-dd** [comment]
Create a CSS modules file and use the [apply directive](https://tailwindcss.com/docs/functions-and-directives#apply) there.

For example, instead of

https://github.com/brc-dd/next-hash-classnames/blob/e10be05ba2e87b8f87e75b50748d8124ba3df170/styles/index.module.css#L1-L4

you can write:

```css
.foo {
  @apply text-2xl;
}
```

If you don't want to do this, use something like [twin.macro](https://github.com/ben-rogerson/twin.macro).
